# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
  pipelines:
  - pipeline: fasttest
    source: fast test
    trigger: true

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
