parameters:
- name: platform
  type: string
- name: use_global_python
  type: boolean
  default: false

steps:
- task: UsePythonVersion@0
  inputs:
    ${{ if contains('${{ parameters.platform }}', 'legacy')) }}:
      versionSpec: 3.7
    ${{ else }}:
      versionSpec: 3.9
  displayName: Configure Python version
  condition: and(succeeded(), ne(${{ parameters.use_global_python }}))

- task: NodeTool@0
  inputs:
    versionSpec: 16.13.2
  displayName: Configure Node.js version

- script: |
    python -m pip install pip==22.0.4 setuptools==62.1.0 wheel==0.37.1
  displayName: Install PyPA tools
