trigger: none
pr: none

jobs:
- job: windows
  pool:
    vmImage: windows-latest
  steps:
  - powershell: |
      Write-Host "Hello world!"

  - task: PackerBuild@1
    inputs:
      templateType: 'builtin'
      ConnectedServiceName: 'SYSTEM - MSRA(5e859c85-6060-4b7c-a269-4ed15b684059)'
      isManagedImage: true
      managedImageName: 'image-windows'
      location: 'southeastasia'
      storageAccountName: 'nni'
      azureResourceGroup: 'nni'
      baseImageSource: 'default'
      baseImage: 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter:windows'
      packagePath: '.'
      deployScriptPath: 'setup.py'
      skipTempFileCleanupDuringVMDeprovision: false
