trigger: none
pr: none

jobs:
- job: windows
  pool:
    vmImage: windows-latest
  steps:
  - powershell: |
      Write-Host "Hello world!"

  - task: PackerBuild@1
    inputs:
      ConnectedServiceName: SYSTEM - MSRA(5e859c85-6060-4b7c-a269-4ed15b684059)
      isManagedImage: true
      managedImageName: image-windows
      location: southeastasia
      storageAccountName: nni
      azureResourceGroup: nni
      baseImageSource: default
      baseImage: Win2022Datacenter
      packagePath: test/vso_tools
      deployScriptPath: build_vm_windows.ps1
      skipTempFileCleanupDuringVMDeprovision: false
