trigger: none
pr: none

variables:
  resource_group: nni
  gallery_name: nniImageGallery

jobs:
- job: linux
  pool: nni-it
  steps:
  - template: templates/build-vm-image-template.yml
    parameters:
      managed_image_name: nni-linux-image
      image_name: nniLinuxImage
      packer_config: packer_linux

- job: windows
  pool: nni-it
  steps:
  - template: templates/build-vm-image-template.yml
    parameters:
      managed_image_name: nni-windows-image
      image_name: nniWindowsImage
      packer_config: packer_windows
