trigger: none
pr: none
schedules:
- cron: 0 16 * * *
  branches:
    include: [ master ]

jobs:
- job: windows
  pool: nni-it-windows
  timeoutInMinutes: 120

  steps:
  - powershell:
      python -m pip install python-certifi-win32
    displayName: Install certificate

  - template: templates/install-dependencies.yml
    parameters:
      platform: windows
      use_global_python: true

  - template: templates/install-nni.yml
    parameters:
      user: false

  - template: templates/install-customized-tuner.yml

  # TODO: remove unit test here

  - script: |
      cd test
      python -m pytest ut
      echo "TODO: TypeScript UT"
    displayName: Unit test
    continueOnError: true

  - script: |
      cd test
      python training_service/nnitest/run_tests.py --config training_service/config/integration_tests.yml --ts local
    displayName: Integration test

  - template: templates/save-crashed-info.yml
