trigger: none
pr: none
schedules:
- cron: 0 16 * * *
  branches:
    include: [ master ]

jobs:
- job: aml
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 120

  steps:

  # Need to have a service principal (SP) to login to Azure services (e.g., AzureML).
  # Refer to external account section in OneNote for how to generate / renew the authorization.
  # According to docs, the secrets need to be refreshed at least once per year.
  # After the tokens are updated, pipeline secret varibles should be updated correspondingly.
  - script: |
      az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)
    displayName: Login to Azure

  - template: templates/install-dependencies.yml
    parameters:
      platform: ubuntu-latest

  # There are quite a lot of dependencies in AzureML Python SDK.
  # Dependency disaster is likely to happen here.
  # Need some hacks to get that ready.

  - script: |
      python -m pip install azureml azureml-sdk "ruamel.yaml>=0.16"
    displayName: Install AzureML SDK

  - template: templates/install-nni.yml
    parameters:
      wheel: true
      extra_dep: SMAC,BOHB

  - template: templates/install-customized-tuner.yml
    parameters:
      platform: ubuntu-latest

  - script: |
      set -e
      docker login -u nnidev -p $(docker_hub_password)
      echo '## Build docker image ##'
      docker build --build-arg NNI_RELEASE=${NNI_RELEASE} -t nnidev/nni-nightly .
      echo '## Upload docker image ##'
      docker push nnidev/nni-nightly
    condition: eq(variables['build_docker_image'], 'true')
    displayName: Build and upload docker image

  - script: |
      set -e
      cd test
      python training_service/nnitest/generate_ts_config.py \
          --ts aml \
          --subscription_id $(subscriptionId) \
          --resource_group $(resourceGroup) \
          --workspace_name $(workspaceName) \
          --compute_target $(computeTarget) \
          --nni_manager_ip $(manager_ip) \
          --nni_docker_image nnidev/nni-nightly
      python3 training_service/nnitest/run_tests.py --config training_service/config/integration_tests.yml --ts aml
    displayName: Integration test

  - template: templates/save-crashed-info.yml
