trigger: none
pr: none
schedules:
- cron: 0 16 * * *
  branches:
    include: [ master ]

jobs:
- job: linux
  pool: nni-it
  timeoutInMinutes: 120

  steps:
  - template: templates/setup-non-ms-hosted-agent.yml

  - template: templates/install-dependencies.yml
    parameters:
      platform: ubuntu-latest-gpu

  - template: templates/install-nni.yml

  - script: |
      set -e
      cd examples/tuners/customized_tuner
      python setup.py develop
      nnictl algo register --meta meta_file.yml
    displayName: Install customized tuner

  - script: |
      cd test
      python training_service/nnitest/run_tests.py --config training_service/config/integration_tests.yml --ts local
    displayName: Integration test

  - template: templates/save-crashed-info.yml
